### PR TITLE
Pandas-like Apply() functionality for the db

### PR DESCRIPTION
**Pull request by Racopokemon**
Note, that unlike Pandas the apply() call does an in-place remplacement of the db-entries. 
One could therefore consider to relabel the function to apply_inplace() instead. 

Also the repair() and delete_if() calls are now powered by the apply() call, which improves their performance. The previous implementation copied the database twice, now data is only copied / rewritten once.

### CODE REVIEW

**Comment by d-krupke** [comment]
The test seems to contain an explicit call of the test function. Could you either remove it or guard it via `__name__=="__main__"` please?  Otherwise,  it may crashes the test environment in case in fails in the future.

**Comment by Racopokemon** [comment]
You are totally right! This is fixed now.

**Comment by d-krupke** [comment]
Thanks!

**Comment by d-krupke** [comment]
I believe that there could be a problem with 'apply' if the folder "old_db" exists by chance. Maybe it would be safer to use a unique folder name?

**Comment by Racopokemon** [comment]
This is indeed a good idea! I've adapted the code, the directory name now includes both a timestamp (maybe useful for debugging) and a random number.

**Comment by d-krupke** [comment]
The current implementation of apply only takes care of the data part, but not of the fingerprints and the environment data. I added a new test case that shows the problematic behavior.

**Comment by Racopokemon** [comment]
Thank you for pointing this out, I will work on a solution.

**Comment by d-krupke** [comment]
You will essentially have to move the old data base and then fill the now empty one anew. Maybe it could be useful to implement a 'move_and_clear' method for this.

**Comment by Racopokemon** [comment]
The issue is fixed on this branch, however I realized there is a smarter way to implement this feature. 
I will therefore close this request and create a new pull request.

**Pull request closed without merging**
