### PR TITLE
File splits

### PR DESCRIPTION
**Pull request by Racopokemon**
Simple implementation of automatic file splits (right now at 30 MB) for experiment data

### CODE REVIEW

**Comment by d-krupke** [comment]
How  sure are you that there cannot be any deep or possibly infinite recursions in flush<->_get_unique_name? This looks suspicious to me.

**Comment by Racopokemon** [comment]
I don't think this is a problem. _get_unique_name recurses at most 7 times and does no other calls to the nfs_json_list while on it, especially no calls that cause a flush() call. flush() also does not make calls that could cause a second, nested flush() call.

**Comment by d-krupke** [comment]
flush calls _get_unique_name and _get_unique_name calls flush. So there is a nesting, if I my diff of the code isn't wrong.

**Comment by Racopokemon** [comment]
I guess you refer to the flush()-call in line 59? This call actually happens as first line of the compress() function, which is omitted by the diff view. _get_unique_name ends just before. 
The flush() call in compress() should normally make no difference, but if someone decided to add entries without flushing, it makes sense to do this once before compressing all files - this is the reason behind this line.

**Comment by d-krupke** [comment]
Indeed. The diff was misleading.

**Pull request merged**
